---
title: "Practicum 1 Technical Report"
author: "Bilal Mozaffar, Risheng Li, Thomas Janes"
date: "2/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Libraries}
library(tidyr)
library(ggplot2)
```

```{r Read Data}
dat <- read.csv('Practicum 1 Data.csv', header = TRUE)

names(dat)[names(dat) == "Vig ex Time"] <- "Vig.ex.Time"
names(dat)[names(dat) == "Mod ex time"] <- "Mod.ex.time"
names(dat)[names(dat) == "Walk ex Time"] <- "Walk.ex.Time"

dat1 <- dat[, c("shift", "gender", "Age", "height", "weightgain", "lbs_gained", "bweight", "BMI", "Vig.ex.Time", "Mod.ex.time", "Walk.ex.Time", "Total_Met_Min")]
```

```{r Fill in missing falues of Total_Met_Min}
i = 1
for (obs in dat1$Total_Met_Min){
  
  if (obs == "" || is.na(obs)) {
    dat1$Total_Met_Min[i] = (8 * as.numeric(dat1$Vig.ex.Time[i])) + (4 * as.numeric(dat1$Mod.ex.time[i])) + (3.3 * as.numeric(dat1$Walk.ex.Time[i]))
  }
  
  if (is.na(dat1$Total_Met_Min[i]) || dat1$Total_Met_Min[i] == 0) { #keep values where Total_Met_Min=0?
    dat1 = dat1[-i,]
  } else {
    i = i + 1
  }
  
}
```

```{r Remove missing lbs_gained values}
i = 1
for (obs in dat1$lbs_gained) {
  if (obs == "" || is.na(obs)) {
    dat1 = dat1[-i,]
  } else {
    i = i + 1
  }
}
```

```{r Changed Total_Met_Min to continuous variable}
dat1$Total_Met_Min = as.numeric(dat1$Total_Met_Min)
```

```{r Linear Model}
lm = lm(lbs_gained ~ Total_Met_Min, data = dat1)

summary(lm)
```

```{r First Scatterplot}
ggplot(data = dat1, aes(x = Total_Met_Min, y = lbs_gained)) + geom_point() + geom_smooth()
```

```{r Remove lbs_gained values > 45}
i = 1
for (obs in dat1$lbs_gained) {
  if (obs > 45) {
    dat1 = dat1[-i,]
  } else {
    i = i + 1
  }
}
```

```{r Remove Total_Met_Min values > 5000}
i = 1
for (obs in dat1$Total_Met_Min) {
  if (obs >= 5000) {
    dat1 = dat1[-i,]
  } else {
    i = i + 1
  }
}
```

```{r Linear Model without outliers}
lm = lm(lbs_gained ~ Total_Met_Min, data = dat1)

summary(lm)
```
P-value got bigger

```{r Second Scatterplot}
ggplot(data = dat1, aes(x = Total_Met_Min, y = lbs_gained)) + geom_point() + geom_smooth()
```


### Risheng: replace lbs_gained value with 0 if weightgain = 0 and drop the rows that both weightgain and lbs_gained are missing. Also calculate the beginning weight by subtracting lbs_gain from body weight. Calculate the change in BMI using begeinning weight and height.
```{r}
dat1$lbs_gained[dat1$weightgain == "No"] <- 0

dat1 %>% 
  filter_at(vars(weightgain, lbs_gained), any_vars(complete.cases(.)))

dat1$beg_weight <- dat1$bweight - dat1$lbs_gained

dat1$Beg_BMI <- (dat1$beg_weight/(dat1$height^2))*703
dat1$BMIChange <- dat1$BMI - dat1$Beg_BMI

```

```{r}
dat1$weightgain.b <- ifelse(dat1$weightgain == 'Yes', 1, 0)

head(dat1)
head(dat)

dat1$gender <- factor(dat1$gender)
dat1$shift <- factor(dat1$shift)


mod1 <- glm(weightgain.b ~ shift + gender + Age + height + Vig.ex.Time + Mod.ex.time + Walk.ex.Time + Total_Met_Min, family = binomial,na.omit(dat1))

##qq plot
qqnorm(residuals(mod1))

##Outliers: no obvious outliers
halfnorm(residuals(mod1))

## test if shift should be removed from the model
mod0 <- glm(weightgain.b ~ gender + Age + height + Vig.ex.Time + Mod.ex.time + Walk.ex.Time + Total_Met_Min, family = binomial,na.omit(dat1))

summary(mod1)
summary(mod0)

anova(mod0, mod1, test = "Chi")

##do not reject the null hypothesis that the reduced model is better, therefore should include shift in the model
```

```{r}
## Using stepwise to select the best model
mod00 <- glm(weightgain.b ~ 1, family = binomial,na.omit(dat1))

m.sw1 = step(mod00,
            scope=list(lower=mod00, upper=mod1),
            direction = "both", trace = F)

m.sw1$anova

## The selected model with the lowest AIC contains only two variables: gender and Total_Met_Min, therefore the Total_Met_Min does have an effect on weight gain, and shift does not have a significant effect on weight gain

```







